### <b>Create apple dataframe

In [2]:
# 1.) import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
import pandas_ta
import datetime as dt
import re
import pandas_datareader.data as web
from pandas_datareader import data as pdr
import yfinance as yf
yf.pdr_override()
import warnings
warnings.filterwarnings('ignore')

In [3]:
# 2.) import data

ebay_fin = pd.read_csv('ebay.csv')
ebay_fin.head()

,Date,Close,eps_q,book_value,de_ratio,npm,gold,crudeoil,sp500,ndx,fed,rsi,MACD
0,2013-01-02,22.554714,0.020395,882.875297,0.028030,0.007753,163.169998,93.120003,1462.420044,2746.469971,0.17,0.000000,0.000000
1,2013-01-03,22.074917,0.020838,902.064553,0.028639,0.007921,161.199997,92.919998,1459.369995,2732.260010,0.17,0.000000,-0.010765
2,2013-01-04,22.213804,0.020708,896.424574,0.028460,0.007872,160.440002,93.089996,1466.469971,2724.489990,0.16,22.448816,-0.009409
3,2013-01-07,22.521044,0.020425,884.195253,0.028072,0.007765,159.429993,93.190002,1461.890015,2724.219971,0.16,48.181794,0.002530
4,2013-01-08,22.171717,0.020747,898.126215,0.028514,0.007887,160.559998,93.150002,1457.150024,2718.719971,0.15,34.983450,-0.004936

In [4]:
# 3.) add more technical indicators

# calculate sma
ebay_fin['SMA21'] = ebay_fin['Close'].rolling(window = 21).mean()

# calculate bband
window_size = 20
num_std_dev = 2
rolling_mean = ebay_fin['Close'].rolling(window = window_size).mean()
rolling_std = ebay_fin['Close'].rolling(window = window_size).std()

ebay_fin['bbupper'] = rolling_mean + (num_std_dev * rolling_std)
ebay_fin['bblower'] = rolling_mean - (num_std_dev * rolling_std)

ebay_fin.bfill(inplace=True)
display(ebay_fin.head())
ebay_fin.to_csv('ebay_final.csv')

,Date,Close,eps_q,book_value,de_ratio,npm,gold,crudeoil,sp500,ndx,fed,rsi,MACD,SMA21,bbupper,bblower
0,2013-01-02,22.554714,0.020395,882.875297,0.028030,0.007753,163.169998,93.120003,1462.420044,2746.469971,0.17,0.000000,0.000000,22.712642,23.742261,21.598647
1,2013-01-03,22.074917,0.020838,902.064553,0.028639,0.007921,161.199997,92.919998,1459.369995,2732.260010,0.17,0.000000,-0.010765,22.712642,23.742261,21.598647
2,2013-01-04,22.213804,0.020708,896.424574,0.028460,0.007872,160.440002,93.089996,1466.469971,2724.489990,0.16,22.448816,-0.009409,22.712642,23.742261,21.598647
3,2013-01-07,22.521044,0.020425,884.195253,0.028072,0.007765,159.429993,93.190002,1461.890015,2724.219971,0.16,48.181794,0.002530,22.712642,23.742261,21.598647
4,2013-01-08,22.171717,0.020747,898.126215,0.028514,0.007887,160.559998,93.150002,1457.150024,2718.719971,0.15,34.983450,-0.004936,22.712642,23.742261,21.598647